    var cl = document.getElementsByClassName('show');
    createLunbo(cl[0], [
        { imgUrl: './img/jm/jm.jpg' },
        { imgUrl: './img/jm/jm2.jpg' },
        { imgUrl: './img/jm/jm3.jpg' },
        { imgUrl: './img/jm/jm4.jpg' },
        { imgUrl: './img/jm/jm5.jpg' },
        { imgUrl: './img/jm/jm6.jpg' },
        { imgUrl: './img/jm/jm7.jpg' },
        { imgUrl: './img/jm/jm8.jpg' },
        { imgUrl: './img/jm/jm9.jpg' },
        { imgUrl: './img/jm/jm10.jpg' },
        { imgUrl: './img/jm/jm11.jpg' },
        { imgUrl: './img/jm/jm12.jpg' },
    ]);
    createLunbo(cl[1], [
        { imgUrl: './img/gmgy/gmdt2.jpg' },
        { imgUrl: './img/gmgy/gemie.jpg' },
        { imgUrl: './img/gmgy/gmdt.jpg' },
        { imgUrl: './img/gmgy/gmdt1.jpg' },
        { imgUrl: './img/gmgy/gmdt3.jpg' },
        { imgUrl: './img/gmgy/gmdt4.jpg' },
        { imgUrl: './img/gmgy/gmdt5.jpg' },
        { imgUrl: './img/gmgy/gmdt6.jpg' },
    ]);
    createLunbo(cl[2], [
        { imgUrl: './img/lvdi/lvdi.jpg' },
        { imgUrl: './img/lvdi/lvdi1.jpg' },
        { imgUrl: './img/lvdi/lvdi2.jpg' },
        { imgUrl: './img/lvdi/lvdi3.jpg' },
        { imgUrl: './img/lvdi/jt.jpg' },
    ]);
    createLunbo(cl[3], [
        { imgUrl: './img/zd/zd14.jpg' },
        { imgUrl: './img/zd/zd1.jpg' },
        { imgUrl: './img/zd/zd2.jpg' },
        { imgUrl: './img/zd/zd3.jpg' },
        { imgUrl: './img/zd/zd5.jpg' },
        { imgUrl: './img/zd/zd6.jpg' },
        { imgUrl: './img/zd/zd7.jpg' },
        { imgUrl: './img/zd/zd8.jpg' },
        { imgUrl: './img/zd/zd9.jpg' },
        { imgUrl: './img/zd/zd10.jpg' },
        { imgUrl: './img/zd/zd11.jpg' },
        { imgUrl: './img/zd/zd12.jpg' }
    ]);
    createLunbo(cl[4], [
        { imgUrl: './img/mytd/mytd.jpg' },
        { imgUrl: './img/mytd/mytd1.jpg' },
        { imgUrl: './img/mytd/mytd2.jpg' },
        { imgUrl: './img/mytd/mytd3.jpg' },
        { imgUrl: './img/mytd/mytd4.jpg' },
        { imgUrl: './img/mytd/mytd5.jpg' },
        { imgUrl: './img/mytd/mytd6.jpg' },
        { imgUrl: './img/mytd/mytd7.jpg' },
        { imgUrl: './img/mytd/mytd8.jpg' },
        { imgUrl: './img/mytd/mytd9.jpg' },
        { imgUrl: './img/mytd/mytd10.jpg' }
    ]);
    createLunbo(cl[5], [
        { imgUrl: './img/zzhx/zzhx.jpg' },
        { imgUrl: './img/zzhx/zzhx1.jpg' },
        { imgUrl: './img/zzhx/zzhx2.jpg' },
        { imgUrl: './img/zzhx/zzhx3.jpg' },
        { imgUrl: './img/zzhx/zzhx5.jpg' },
        { imgUrl: './img/zzhx/zzhx6.jpg' },
        { imgUrl: './img/zzhx/zzhx7.jpg' },
        { imgUrl: './img/zzhx/zzhx8.jpg' },
        { imgUrl: './img/zzhx/zzhx9.jpg' },
        { imgUrl: './img/zzhx/zzhx10.jpg' },
        { imgUrl: './img/zzhx/zzhx11.jpg' },
        { imgUrl: './img/zzhx/zzhx12.jpg' },
        { imgUrl: './img/zzhx/zzhx13.jpg' },
        { imgUrl: './img/zzhx/zzhx14.jpg' },
        { imgUrl: './img/zzhx/zzhx15.jpg' },
        { imgUrl: './img/zzhx/zzhx16.jpg' },
        { imgUrl: './img/zzhx/zzhx17.jpg' },
        { imgUrl: './img/zzhx/zzhx18.jpg' },
        { imgUrl: './img/zzhx/zzhx19.jpg' },
        { imgUrl: './img/zzhx/zzhx20.jpg' },
        { imgUrl: './img/zzhx/zzhx21.jpg' },
        { imgUrl: './img/zzhx/zzhx22.jpg' },
        { imgUrl: './img/zzhx/zzhx23.jpg' },
        { imgUrl: './img/zzhx/zzhx24.jpg' },
        { imgUrl: './img/zzhx/zzhx25.jpg' },
    ]);
    createLunbo(cl[6], [
        { imgUrl: './img/yltj/yltj.jpg' },
        { imgUrl: './img/yltj/yltj2.jpg' },
        { imgUrl: './img/yltj/yltj3.jpg' },
        { imgUrl: './img/yltj/yltj4.jpg' },
        { imgUrl: './img/yltj/yltj5.jpg' },
        { imgUrl: './img/yltj/yltj6.jpg' },
        { imgUrl: './img/yltj/yltj7.jpg' },
        { imgUrl: './img/yltj/yltj8.jpg' },
        { imgUrl: './img/yltj/yltj9.jpg' },
        { imgUrl: './img/yltj/yltj10.jpg' },
        { imgUrl: './img/yltj/yltj11.jpg' }
    ]);